### ISSUE TITLE
[Doc] Add Supported LLMs to README

### ISSUE THREAD

**Issue by Anonymitaet** [TEN-framework/ten-framework#42]
Hi Astra,

Greetings from 01.AI. Thank you for building this wonderful project and integrating Yi! 😘

As discussed with @cyfyifanchen today, we both think adding a "Supported LLMs" section to Astra's README is a good idea, as it 1) showcases Astra's thriving ecosystem 2) helps users locate desired info more quickly

Example:
[Supported LLMs List of LlaMA-Factory](https://github.com/hiyouga/LLaMA-Factory?tab=readme-ov-file#supported-models)
<img width="755" alt="image" src="https://github.com/rte-design/ASTRA.ai/assets/50226895/e41a0a3f-a31c-40a8-ba8d-8f042e86fc96">

If this suggestion is accepted and implemented by Astra, could you please add "Yi" to the "Supported LLMs" list? 

Feel free to let me know if you have any questions or concerns. Thank you!  🙌

**Comment by cyfyifanchen** [comment]
The very first issue from the community, gotta love it.

**Comment by cyfyifanchen** [comment]
Now it has a ready-to-use extensions to inform users available extensions.
