### ISSUE TITLE
[BUG] agent can not talk and hear

### ISSUE THREAD

**Issue by fanqingsong** [TEN-framework/ten-framework#455]
### Description

Hello , when I run ten agent , I encountered such issue, 
The greeting words can be displayed in web gui, 
but no voice generated, and when I talked, there is no response from agent.
I checked the log , there is such error log , please help debug.
thanks.

![图片](https://github.com/user-attachments/assets/3d9b9953-c468-425e-8b01-df03ec51bb15)

### Environment

WSL ubuntu

### Steps to reproduce

after run agent,  operate on webui.

### Expected behavior

agent can talk and hear

### Severity

Critical

**Comment by plutoless** [comment]
@fanqingsong according to the logs, there's sth wrong with your azure stt key.

**Comment by fanqingsong** [comment]
Thanks， you can close this ticket.
